import "ClipboardSnapshot.idl";

namespace Rememory.Core
{
    [default_interface]
    runtimeclass ClipboardMonitor
    {
        String HistoryFolderPath{ get; set; };
        UInt64 MaxDataSize{ get; set; };

        ClipboardMonitor();
        void StartMonitoring(UInt64 windowHandle);
        void StopMonitoring();


        //[interface_name("Rememory.Core.IClipboardWriter")]
        Boolean SetClipboardData(Windows.Foundation.Collections.IMapView<ClipboardFormat, String> dataMap);

        //[interface_name("Rememory.Core.IClipboardEvents")]
        event Windows.Foundation.TypedEventHandler<ClipboardMonitor, Rememory.Core.ClipboardSnapshot> ContentDetected;
    }
}
