import "FormatManager.idl";

namespace Rememory.Core
{
    [default_interface]
    runtimeclass FormatRecord
    {
        ClipboardFormat Format { get; set; };
        String Data { get; set; };
        Windows.Storage.Streams.IBuffer Hash { get; set; };

        FormatRecord();
    };
}
